services:
  judge0:
    image: judge0/judge0:latest-dev
    build:
      context: .
      target: development
    volumes:
      - .:/api
    env_file: judge0.conf
    ports:
      - "2358:2358"
      - "3001:3001" # For ./scripts/dev/serve-docs
    privileged: true

  db:
    image: postgres:16.2
    env_file: judge0.conf
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    command:
      [
        "bash",
        "-c",
        'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"',
      ]
    env_file: judge0.conf
    restart: always

volumes:
  data:
